// Cross-verifies facelet-cube.js against ground truth produced by the real
// `magiccube` Python package (see PROJECT_STATUS.md's standing "verify
// empirically, don't hand-derive rotation algebra" rule). facelet-fixture.json
// was generated by gen_facelet_fixture.py, which runs 300 random
// algorithms (length 1-30, full face-turn + whole-cube-rotation move set)
// plus every single move in isolation through `magiccube` and records the
// resulting facelet string.

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { applyAlgorithm, SOLVED_FACELETS, isMoveToken } = require('../facelet-cube.js');

let passCount = 0;
function check(name, condition) {
    if (condition) {
        passCount++;
        console.log(`PASS: ${name}`);
    } else {
        console.error(`FAIL: ${name}`);
        process.exitCode = 1;
    }
}

const fixturePath = path.join(__dirname, 'facelet-fixture.json');
const cases = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));

check('fixture file is non-empty', cases.length > 0);

let allMatch = true;
let firstMismatch = null;
for (const { moves, facelets } of cases) {
    const got = applyAlgorithm(SOLVED_FACELETS, moves.join(' '));
    if (got !== facelets) {
        allMatch = false;
        if (!firstMismatch) firstMismatch = { moves, expected: facelets, got };
    }
}
check(
    `all ${cases.length} magiccube-derived cases match (quarter turns, doubles, primes, whole-cube rotations, compositions)`,
    allMatch
);
if (!allMatch) {
    console.error('First mismatch:', JSON.stringify(firstMismatch, null, 2));
}

// Basic algebraic sanity checks (identities any correct implementation must satisfy).
check(
    'U^4 returns to the solved state',
    applyAlgorithm(SOLVED_FACELETS, 'U U U U') === SOLVED_FACELETS
);
check(
    "R R' is a no-op from solved",
    applyAlgorithm(SOLVED_FACELETS, "R R'") === SOLVED_FACELETS
);
check(
    'F2 equals F F',
    applyAlgorithm(SOLVED_FACELETS, 'F2') === applyAlgorithm(SOLVED_FACELETS, 'F F')
);
check(
    "y y' is a no-op from solved",
    applyAlgorithm(SOLVED_FACELETS, "y y'") === SOLVED_FACELETS
);
check(
    'x4 returns to the solved state',
    applyAlgorithm(SOLVED_FACELETS, 'x x x x') === SOLVED_FACELETS
);
check(
    'cleanScramble-style "none" placeholder is stripped',
    applyAlgorithm(SOLVED_FACELETS, 'none') === SOLVED_FACELETS
);
check(
    'unrecognized move token throws instead of silently no-opping',
    (() => {
        try {
            applyAlgorithm(SOLVED_FACELETS, 'Rw');
            return false;
        } catch (e) {
            return /unrecognized move token/.test(e.message);
        }
    })()
);
check('isMoveToken recognizes a standard face turn', isMoveToken('R2'));
check('isMoveToken rejects unknown notation (Rw: wide moves are written lowercase here)', !isMoveToken('Rw') && !isMoveToken('Q'));
check('isMoveToken accepts wide, slice and X2\' tokens', ['r', "u'", 'M2', 'E', "S'", "R2'"].every(isMoveToken));

// canonicalizeForEngine (§4.19): state(prefix, alg) == state(rotation, moves),
// with `moves` face turns only, for random mixed-notation sequences.
{
    const { canonicalizeForEngine } = require('../facelet-cube.js');
    const V = [...'UDRLFBxyzrludfbMES'].flatMap(f => [f, f + "'", f + '2']);
    let seed = 3;
    const rnd = () => { seed = (seed * 16807) % 2147483647; return seed / 2147483647; };
    const start = applyAlgorithm(SOLVED_FACELETS, "R U2 F' D L2 B");
    let bad = 0;
    for (let i = 0; i < 1000; i++) {
        const alg = Array.from({ length: 1 + Math.floor(rnd() * 15) }, () => V[Math.floor(rnd() * V.length)]).join(' ');
        const pre = ['', 'z2', 'x', 'z2 y', "x' y2"][i % 5];
        const c = canonicalizeForEngine(pre, alg);
        const faceOnly = c.moves.split(' ').filter(Boolean).every(t => /^[UDRLFB]['2]?$/.test(t));
        if (!faceOnly || applyAlgorithm(start, [pre, alg].join(' ')) !== applyAlgorithm(start, [c.rotation, c.moves].join(' '))) bad++;
    }
    check(`canonicalizeForEngine preserves the state and emits face turns only (1000 random wide/slice/rotation sequences, ${bad} bad)`, bad === 0);
    check('canonicalizeForEngine: "u" is D + y', canonicalizeForEngine('', 'u').rotation === 'y' && canonicalizeForEngine('', 'u').moves === 'D');
}

{
    const { inverseRotation } = require('../facelet-cube.js');
    const rots = ['', 'y', "y'", 'y2', 'x', 'z2 y', "x' y2", "z y'"];
    check('inverseRotation undoes every tested rotation', rots.every(r =>
        applyAlgorithm(SOLVED_FACELETS, [r, inverseRotation(r)].filter(Boolean).join(' ')) === SOLVED_FACELETS));
}

if (process.exitCode) {
    console.error(`\n${passCount}/${cases.length + 8} checks passed.`);
} else {
    console.log('\nAll facelet-cube.js tests passed.');
}
