// Cross-verifies facelet-cube.js against ground truth produced by the real
// `magiccube` Python package (see PROJECT_STATUS.md's standing "verify
// empirically, don't hand-derive rotation algebra" rule). facelet-fixture.json
// was generated by gen_facelet_fixture.py, which runs 300 random
// algorithms (length 1-30, full face-turn + whole-cube-rotation move set)
// plus every single move in isolation through `magiccube` and records the
// resulting facelet string.

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { applyAlgorithm, SOLVED_FACELETS, isMoveToken } = require('../js/facelet-cube.js');

let passCount = 0;
function check(name, condition) {
    if (condition) {
        passCount++;
        console.log(`PASS: ${name}`);
    } else {
        console.error(`FAIL: ${name}`);
        process.exitCode = 1;
    }
}

const fixturePath = path.join(__dirname, 'facelet-fixture.json');
const cases = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));

check('fixture file is non-empty', cases.length > 0);

let allMatch = true;
let firstMismatch = null;
for (const { moves, facelets } of cases) {
    const got = applyAlgorithm(SOLVED_FACELETS, moves.join(' '));
    if (got !== facelets) {
        allMatch = false;
        if (!firstMismatch) firstMismatch = { moves, expected: facelets, got };
    }
}
check(
    `all ${cases.length} magiccube-derived cases match (quarter turns, doubles, primes, whole-cube rotations, compositions)`,
    allMatch
);
if (!allMatch) {
    console.error('First mismatch:', JSON.stringify(firstMismatch, null, 2));
}

// Basic algebraic sanity checks (identities any correct implementation must satisfy).
check(
    'U^4 returns to the solved state',
    applyAlgorithm(SOLVED_FACELETS, 'U U U U') === SOLVED_FACELETS
);
check(
    "R R' is a no-op from solved",
    applyAlgorithm(SOLVED_FACELETS, "R R'") === SOLVED_FACELETS
);
check(
    'F2 equals F F',
    applyAlgorithm(SOLVED_FACELETS, 'F2') === applyAlgorithm(SOLVED_FACELETS, 'F F')
);
check(
    "y y' is a no-op from solved",
    applyAlgorithm(SOLVED_FACELETS, "y y'") === SOLVED_FACELETS
);
check(
    'x4 returns to the solved state',
    applyAlgorithm(SOLVED_FACELETS, 'x x x x') === SOLVED_FACELETS
);
check(
    'cleanScramble-style "none" placeholder is stripped',
    applyAlgorithm(SOLVED_FACELETS, 'none') === SOLVED_FACELETS
);
check(
    'unrecognized move token throws instead of silently no-opping',
    (() => {
        try {
            applyAlgorithm(SOLVED_FACELETS, 'Rw');
            return false;
        } catch (e) {
            return /unrecognized move token/.test(e.message);
        }
    })()
);
check('isMoveToken recognizes a standard face turn', isMoveToken('R2'));
check('isMoveToken rejects unknown notation (Rw: wide moves are written lowercase here)', !isMoveToken('Rw') && !isMoveToken('Q'));
check('isMoveToken accepts wide, slice and X2\' tokens', ['r', "u'", 'M2', 'E', "S'", "R2'"].every(isMoveToken));

// canonicalizeForEngine (§4.19): state(prefix, alg) == state(rotation, moves),
// with `moves` face turns only, for random mixed-notation sequences.
{
    const { canonicalizeForEngine } = require('../js/facelet-cube.js');
    const V = [...'UDRLFBxyzrludfbMES'].flatMap(f => [f, f + "'", f + '2']);
    let seed = 3;
    const rnd = () => { seed = (seed * 16807) % 2147483647; return seed / 2147483647; };
    const start = applyAlgorithm(SOLVED_FACELETS, "R U2 F' D L2 B");
    let bad = 0;
    for (let i = 0; i < 1000; i++) {
        const alg = Array.from({ length: 1 + Math.floor(rnd() * 15) }, () => V[Math.floor(rnd() * V.length)]).join(' ');
        const pre = ['', 'z2', 'x', 'z2 y', "x' y2"][i % 5];
        const c = canonicalizeForEngine(pre, alg);
        const faceOnly = c.moves.split(' ').filter(Boolean).every(t => /^[UDRLFB]['2]?$/.test(t));
        if (!faceOnly || applyAlgorithm(start, [pre, alg].join(' ')) !== applyAlgorithm(start, [c.rotation, c.moves].join(' '))) bad++;
    }
    check(`canonicalizeForEngine preserves the state and emits face turns only (1000 random wide/slice/rotation sequences, ${bad} bad)`, bad === 0);
    check('canonicalizeForEngine: "u" is D + y', canonicalizeForEngine('', 'u').rotation === 'y' && canonicalizeForEngine('', 'u').moves === 'D');
}

{
    const { inverseRotation } = require('../js/facelet-cube.js');
    const rots = ['', 'y', "y'", 'y2', 'x', 'z2 y', "x' y2", "z y'"];
    check('inverseRotation undoes every tested rotation', rots.every(r =>
        applyAlgorithm(SOLVED_FACELETS, [r, inverseRotation(r)].filter(Boolean).join(' ')) === SOLVED_FACELETS));
}

{
    const { rotationSpellings, commuteNormalize, netRotation, inverseRotation, relabelAlgForRotation } = require('../js/facelet-cube.js');
    const start = applyAlgorithm(SOLVED_FACELETS, "R U F' D2 B L");
    const alg = "U R' U' R U' B U B'";
    const sp = rotationSpellings(alg);
    check('rotationSpellings: every spelling is physically "alg, then its rotation"', sp.every(x =>
        applyAlgorithm(start, `${x} ${inverseRotation(netRotation(x))}`) === applyAlgorithm(start, alg)));
    check('rotationSpellings: includes the pro spelling "U R\' U\' R y U\' R U R\'"',
        sp.some(x => commuteNormalize(x) === commuteNormalize("U R' U' R y U' R U R'")));
    check('rotationSpellings(alg, false) never starts with a rotation', rotationSpellings(alg, false).every(x => !/^[xyz]/.test(x)));
    check('commuteNormalize: same-axis runs (incl. rotations/wide) are ordered, others untouched',
        commuteNormalize("y U' R") === "U' y R" && commuteNormalize("D U R") === 'U D R' && commuteNormalize('R U') === 'R U'
        && commuteNormalize('x l R') === 'R l x');
    check('relabelAlgForRotation agrees with the y-variant convention: y + relabel(R) is R then y',
        applyAlgorithm(start, `y ${relabelAlgForRotation('R', 'y')}`) === applyAlgorithm(start, 'R y'));
}

{
    const { inspectionWideVariants, rotationName } = require('../js/facelet-cube.js');
    const start = applyAlgorithm(SOLVED_FACELETS, "R U F' D2 B L U2");
    const V = [...'UDRLFB'].flatMap(f => [f, f + "'", f + '2']);
    let seed = 3, n = 0, bad = 0;
    const rnd = () => { seed = (seed * 16807) % 2147483647; return seed / 2147483647; };
    for (let i = 0; i < 300; i++) {
        const a = Array.from({ length: 8 }, () => V[Math.floor(rnd() * 18)]).join(' ');
        const I = ['z2', 'z2 y', '', "x' y2"][i % 4];
        for (const v of inspectionWideVariants(a)) {
            n++;
            const J = rotationName([I, v.inspection].filter(Boolean).join(' '));
            const same = applyAlgorithm(start, [J, v.alg].filter(Boolean).join(' ')) === applyAlgorithm(start, [I, a].filter(Boolean).join(' '));
            if (!same || !/^(\S+ )?[rl]/.test(v.alg)) bad++;
        }
    }
    check(`inspectionWideVariants: physically identical incl. end orientation, wide move within the first two (${n} variants, ${bad} bad)`, n > 0 && bad === 0);
}

{
    // §4.34: the table-driven canonicalizeForEngine / relabelAlgForRotation /
    // inverseRotation must give exactly what the plain permutation versions
    // (the pre-optimisation code, kept here as the reference) give.
    const F = require('../js/facelet-cube.js');
    const { MOVE_TABLE, composePerm, invertPerm, IDENTITY_PERM } = F;
    const key = p => p.join(',');
    const rotations = [...'xyz'].flatMap(a => [a, a + "'", a + '2']);
    const faces = [...'UDRLFB'].flatMap(f => [f, f + "'", f + '2']);
    const derived = { r: ['L', 'x'], l: ['R', "x'"], u: ['D', 'y'], d: ['U', "y'"], f: ['B', 'z'], b: ['F', "z'"], M: ['R', "L'", "x'"], E: ['U', "D'", "y'"], S: ["F'", 'B', 'z'] };
    const all = [...faces, ...rotations, ...Object.keys(derived).flatMap(n => [n, n + "'", n + '2'])];
    const tokenByPerm = new Map();
    for (const t of all) if (!tokenByPerm.has(key(MOVE_TABLE[t]))) tokenByPerm.set(key(MOVE_TABLE[t]), t);
    const faceByPerm = new Map(faces.map(t => [key(MOVE_TABLE[t]), t]));
    const permOf = s => s.split(' ').filter(Boolean).reduce((a, t) => composePerm(a, MOVE_TABLE[t]), IDENTITY_PERM);
    const inv = t => t.endsWith('2') ? t : t.endsWith("'") ? t.slice(0, -1) : t + "'";
    const prim = tok => { const b = tok.replace(/['2]$/, ''); const parts = derived[b]; if (!parts) return [tok]; if (tok.endsWith("'")) return parts.slice().reverse().map(inv); if (tok.endsWith('2')) return parts.concat(parts); return parts.slice(); };
    const refRelabel = (alg, rot) => { const r = permOf(rot); const ir = invertPerm(r); return alg.split(' ').filter(Boolean).map(t => tokenByPerm.get(key(composePerm(composePerm(ir, MOVE_TABLE[t]), r)))).join(' '); };
    const refCanonMoves = (prefix, alg) => {
        let Q = IDENTITY_PERM; const early = [];
        for (const tok of [prefix, alg].filter(Boolean).join(' ').split(' ').filter(Boolean)) for (const p of prim(tok)) {
            if (rotations.includes(p)) { Q = composePerm(Q, MOVE_TABLE[p]); continue; }
            early.push(composePerm(composePerm(Q, MOVE_TABLE[p]), invertPerm(Q)));
        }
        const iQ = invertPerm(Q);
        return { Q, moves: early.map(e => faceByPerm.get(key(composePerm(composePerm(iQ, e), Q)))).join(' ') };
    };
    let seed = 11, bad = 0;
    const rnd = () => { seed = (seed * 16807) % 2147483647; return seed / 2147483647; };
    const pick = arr => arr[Math.floor(rnd() * arr.length)];
    for (let i = 0; i < 3000; i++) {
        const alg = Array.from({ length: 1 + Math.floor(rnd() * 14) }, () => pick(all)).join(' ');
        const prefix = Array.from({ length: Math.floor(rnd() * 3) }, () => pick(rotations)).join(' ');
        const got = F.canonicalizeForEngine(prefix, alg);
        const ref = refCanonMoves(prefix, alg);
        if (got.moves !== ref.moves || key(permOf(got.rotation)) !== key(ref.Q)) bad++;
        if (F.relabelAlgForRotation(alg, prefix) !== refRelabel(alg, prefix)) bad++;
        if (key(permOf(F.inverseRotation(prefix))) !== key(invertPerm(permOf(prefix)))) bad++;
    }
    check(`table-driven rotation helpers match the permutation reference on 3000 random mixed-notation algs (${bad} mismatches)`, bad === 0);
}

// Wide-move spellings (README "Wide moves", PROJECT_STATUS.md §4.43).
{
    const F = require('../js/facelet-cube.js');
    const spell = alg => F.wideSpellingParts(alg).map(s => s.alg);
    check('wide spellings: "B U\' B\'" as "f R\' f\'" (no end rotation)',
        F.wideSpellingParts("B U' B'").some(s => s.alg === "f R' f'" && s.rotation === ''));
    check('wide spellings: "D y R U\' R\'" as "u R U\' R\'" (the y is absorbed)', spell("D y R U' R'").includes("u R U' R'"));
    check('wide spellings: "U B U B\'" as "d L U L\'"', spell("U B U B'").includes("d L U L'"));
    check('wide spellings: none for an R/U-only alg', spell("R U R' U' R U R'").length === 0);
    check('wide spellings: never a wide B ("B U\' B\'" has an f spelling only)', !spell("B U' B'").some(a => /(^| )b/.test(a)));
    // Every spelling of random algs: physically "alg, then a y-family
    // rotation", one wide family, at most two wide turns, fewer awkward
    // tokens and no extra F/B turns.
    const faces = [...'UDRLFB'].flatMap(f => [f, `${f}'`, `${f}2`]);
    let seed = 7, bad = 0, total = 0;
    const rnd = () => { seed = (seed * 16807) % 2147483647; return seed / 2147483647; };
    const pick = arr => arr[Math.floor(rnd() * arr.length)];
    const awk = a => a.split(' ').filter(t => /^[DFBxyz]/.test(t)).length;
    const fb = a => a.split(' ').filter(t => /^[FB]/.test(t)).length;
    for (let i = 0; i < 1500; i++) {
        const toks = Array.from({ length: 2 + Math.floor(rnd() * 10) }, () => pick(faces));
        if (rnd() < 0.3) toks.splice(Math.floor(rnd() * toks.length), 0, pick(['y', "y'", 'r', "l'", 'x']));
        const alg = toks.join(' ');
        for (const s of F.wideSpellingParts(alg)) {
            total++;
            const want = F.applyAlgorithm(SOLVED_FACELETS, `${alg} ${s.rotation}`);
            const wide = s.alg.split(' ').filter(t => /^[udfb]/.test(t));
            const ok = F.applyAlgorithm(SOLVED_FACELETS, s.alg) === want
                && ['', 'y', 'y2', "y'"].includes(s.rotation)
                && new Set(wide.map(t => t[0])).size === 1
                && wide.length <= 2 + alg.split(' ').filter(t => /^[rl]/.test(t)).length
                && awk(s.alg) < awk(alg) && fb(s.alg) <= fb(alg);
            if (/(^| )b/.test(s.alg)) bad++; // never a wide B (README "Wide moves")
            if (!ok) bad++;
        }
    }
    check(`wide spellings of 1500 random algs: ${total} spellings, all physically "alg, then rotation" and within the rules (${bad} bad)`, bad === 0 && total > 500);
}

if (process.exitCode) {
    console.error(`\n${passCount}/${cases.length + 14} checks passed.`);
} else {
    console.log('\nAll facelet-cube.js tests passed.');
}
